{
 "title": "Exadata dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"exadata\",metric_name=\"CL_CPUT\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"DS_CPUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utalization",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"exadata\",metric_name=\"CL_MEMUT\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"DS_MEMUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "The percentage of total space utilized on the file system",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"DS_FSUT\"}",
     "legendFormat": "\"{{object_name}}\" in {{node}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"exadata\",metric_name=\"CL_TEMP\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"DS_TEMP\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DB Node Network send/receive rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"N_HCA_MB_RCV_SEC\"}",
     "legendFormat": "the number of megabytes received per second from  {{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"exadata\",metric_name=\"N_HCA_MB_TRANS_SEC\"}",
     "legendFormat": "the number of megabytes received per second from {{node}}"
    }
   ]
  }
 ]
}